import { randomUUID } from 'node:crypto';
import { DatabaseManager } from '../database/DatabaseManager';
import { CompanyDto, SaveCompanyInput } from '../company/company.types';

type CompanyRow = Record<string, string | number | null>;
export class CompanyRepository {
  private readonly database = DatabaseManager.getInstance();
  findCurrent(): CompanyDto | null { const row = this.database.queryOne<CompanyRow>('SELECT * FROM companies WHERE active = 1 ORDER BY id LIMIT 1'); return row ? this.map(row) : null; }
  create(input: SaveCompanyInput): CompanyDto { const uuid = randomUUID(); const id = Number(this.database.execute(`INSERT INTO companies (uuid, legal_name, trade_name, document_number, state_registration, municipal_registration, phone, email, postal_code, street, street_number, complement, district, city, state, country, currency, timezone, backup_path, active) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1)`, [uuid, input.legalName, input.tradeName, input.document ?? null, input.stateRegistration ?? null, input.municipalRegistration ?? null, input.phone ?? null, input.email ?? null, input.postalCode ?? null, input.street ?? null, input.streetNumber ?? null, input.complement ?? null, input.district ?? null, input.city ?? null, input.state ?? null, input.country ?? 'BR', input.currency ?? 'BRL', input.timezone ?? 'America/Sao_Paulo', input.backupPath ?? null]).lastInsertRowid); return this.findById(id)!; }
  update(id: number, input: SaveCompanyInput): CompanyDto { this.database.execute(`UPDATE companies SET uuid=COALESCE(uuid, ?), legal_name=?, trade_name=?, document_number=?, state_registration=?, municipal_registration=?, phone=?, email=?, postal_code=?, street=?, street_number=?, complement=?, district=?, city=?, state=?, country=?, currency=?, timezone=?, backup_path=?, updated_at=CURRENT_TIMESTAMP WHERE id=?`, [randomUUID(), input.legalName, input.tradeName, input.document ?? null, input.stateRegistration ?? null, input.municipalRegistration ?? null, input.phone ?? null, input.email ?? null, input.postalCode ?? null, input.street ?? null, input.streetNumber ?? null, input.complement ?? null, input.district ?? null, input.city ?? null, input.state ?? null, input.country ?? 'BR', input.currency ?? 'BRL', input.timezone ?? 'America/Sao_Paulo', input.backupPath ?? null, id]); return this.findById(id)!; }
  upsertCurrent(input: SaveCompanyInput): CompanyDto { const current = this.findCurrent(); return current ? this.update(current.id, input) : this.create(input); }
  private findById(id: number): CompanyDto | null { const row = this.database.queryOne<CompanyRow>('SELECT * FROM companies WHERE id = ?', [id]); return row ? this.map(row) : null; }
  private map(row: CompanyRow): CompanyDto { return { id: Number(row.id), uuid: String(row.uuid ?? ''), legalName: String(row.legal_name), tradeName: String(row.trade_name), document: row.document_number as string | null, stateRegistration: row.state_registration as string | null, municipalRegistration: row.municipal_registration as string | null, phone: row.phone as string | null, email: row.email as string | null, postalCode: row.postal_code as string | null, street: row.street as string | null, streetNumber: row.street_number as string | null, complement: row.complement as string | null, district: row.district as string | null, city: row.city as string | null, state: row.state as string | null, country: String(row.country ?? 'BR'), logoPath: row.logo_path as string | null, currency: String(row.currency ?? 'BRL'), timezone: String(row.timezone ?? 'America/Sao_Paulo'), backupPath: row.backup_path as string | null }; }
}
