/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-nocheck
/* global CompanyDto, AuthUser */
import './styles.css';
import './auth.css';

type View = 'login' | 'dashboard' | 'change-password' | 'company' | 'products' | 'categories' | 'placeholder';
let currentView: View = 'login';
let placeholderTitle = '';
let user: AuthUser | null = null;
let company: CompanyDto | null = null;
let companyDirty = false;
let products: ProductView[] = []; let categories: CategoryView[] = []; let productEditing: ProductView | null = null; let categoryEditing: CategoryView | null = null;
interface ProductView { id:number; name:string; barcode:string|null; categoryId:number|null; categoryName?:string|null; sku:string; unit:string; costPriceCents:number; salePriceCents:number; marginPercentage:number; currentStockMilli:number; minimumStockMilli:number; active:boolean; description?:string|null; }
interface CategoryView { id:number; name:string; description:string|null; defaultMarginPercentage:number; active:boolean; }
const nav = (view: string, label: string, icon: string, id: string) => `<button class="nav ${currentView === view ? 'active' : ''}" id="${id}"><span>${icon}</span>${label}</button>`;

function loginTemplate(): string { return `<main class="login-page"><section class="brand-panel"><div class="brand-mark">PM</div><p class="eyebrow">GESTÃO INTELIGENTE</p><h1>PDV Master</h1><p>Seu negócio em uma visão simples, rápida e segura.</p></section><section class="login-card"><p class="eyebrow">BEM-VINDO</p><h2>Entrar na plataforma</h2><form id="login-form"><label>E-mail<input name="email" required type="email" /></label><label>Senha<input name="password" required type="password" /></label><p id="auth-error" class="auth-error"></p><button class="primary">Entrar</button></form></section></main>`; }
function changePasswordTemplate(): string { return `<main class="login-page"><section class="brand-panel"><div class="brand-mark">PM</div><h1>Primeiro acesso</h1><p>Defina sua nova senha para continuar.</p></section><section class="login-card"><h2>Alterar senha</h2><form id="change-password-form"><label>Senha atual<input name="currentPassword" required type="password" /></label><label>Nova senha<input name="newPassword" minlength="12" required type="password" /></label><p id="auth-error" class="auth-error"></p><button class="primary">Salvar e continuar</button></form></section></main>`; }
function sidebar(): string { const name = user?.name ?? 'Usuário'; return `<aside class="sidebar" id="sidebar"><div class="side-brand"><div class="brand-mark small">PM</div>${company?.tradeName ?? 'PDV Master'}<button id="close-menu">×</button></div><nav>${nav('dashboard','Visão geral','▦','nav-dashboard')}${nav('placeholder','Vendas','▣','nav-sales')}<div class="nav-section">Cadastros</div>${nav('categories','Categorias','▤','nav-categories')}${nav('products','Produtos','◫','nav-products')}${nav('placeholder','Clientes','♙','nav-customers')}${nav('placeholder','Fornecedores','♧','nav-suppliers')}<div class="nav-section">Configurações</div>${nav('company','Dados da empresa','⚙','nav-company')}</nav><button class="profile" id="logout-button"><b>${name.slice(0, 2).toUpperCase()}</b><span><strong>${name}</strong><small>Sair da sessão</small></span></button></aside>`; }
function dashboardTemplate(): string { const name = user?.name ?? 'Usuário'; return `<main class="shell">${sidebar()}<section class="dashboard"><header><button id="open-menu" class="hamburger">☰</button><div><p class="eyebrow">PAINEL PRINCIPAL</p><h1>Olá, ${name} ✦</h1><p>Acompanhe os principais indicadores do seu negócio.</p></div><button class="theme-toggle">◐</button></header><section class="metrics"><article class="metric"><i>↗</i><p>Vendas hoje</p><strong>R$ 0,00</strong></article><article class="metric"><i>◫</i><p>Produtos cadastrados</p><strong>0</strong></article><article class="metric"><i>♙</i><p>Clientes ativos</p><strong>0</strong></article></section></section></main>`; }
function placeholderTemplate(): string { return `<main class="shell">${sidebar()}<section class="dashboard"><header><button id="open-menu" class="hamburger">☰</button><div><p class="eyebrow">MÓDULO</p><h1>${placeholderTitle}</h1><p>Este módulo está em desenvolvimento.</p></div><button class="theme-toggle">◐</button></header><article class="panel empty-module"><h2>Em desenvolvimento</h2><p>O módulo ${placeholderTitle} será disponibilizado em uma próxima sprint.</p><button id="back-dashboard" class="primary">Voltar para Visão geral</button></article></section></main>`; }
function companyTemplate(): string { const c = company ?? ({} as CompanyDto); const f = (name: string, label: string) => `<label>${label}<input name="${name}" value="${String(c[name as keyof CompanyDto] ?? '')}" /></label>`; return `<main class="shell">${sidebar()}<section class="dashboard company-page"><header><div><p class="eyebrow">CONFIGURAÇÕES</p><h1>Dados da empresa</h1><p>Informações usadas para personalizar o sistema.</p></div></header><form id="company-form" class="company-form"><section class="panel"><h2>Identificação</h2><div class="form-grid">${f('legalName','Razão social')}${f('tradeName','Nome fantasia')}${f('document','CNPJ/CPF')}${f('stateRegistration','Inscrição estadual')}${f('municipalRegistration','Inscrição municipal')}</div></section><section class="panel"><h2>Contato</h2><div class="form-grid">${f('phone','Telefone')}${f('email','E-mail')}</div></section><section class="panel"><h2>Endereço</h2><div class="form-grid">${f('postalCode','CEP')}${f('street','Logradouro')}${f('streetNumber','Número')}${f('complement','Complemento')}${f('district','Bairro')}${f('city','Cidade')}${f('state','Estado')}${f('country','País')}</div></section><section class="panel"><h2>Sistema</h2><div class="form-grid">${f('currency','Moeda')}${f('timezone','Fuso horário')}${f('backupPath','Pasta de backup')}</div><div class="logo-placeholder">Logomarca — recurso disponível posteriormente.</div></section><p id="company-message" class="auth-error"></p><button class="primary" id="company-save">Salvar alterações</button></form></section></main>`; }
const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v/100); const pct=(v:number)=>`${(v/100).toFixed(2)}%`;
function categoriesTemplate():string{return `<main class="shell">${sidebar()}<section class="dashboard"><header><div><p class="eyebrow">CADASTROS</p><h1>Categorias</h1></div><button id="new-category" class="primary">Nova categoria</button></header><div class="catalog-tools"><input id="category-search" placeholder="Pesquisar categoria" /><span id="catalog-message" class="auth-error"></span></div><section class="panel"><div id="category-list">${categories.length?categories.map(c=>`<div class="catalog-row"><b>${c.name}</b><span>${c.description??'—'}</span><span>${pct(c.defaultMarginPercentage)}</span><span class="status ${c.active?'on':'off'}">${c.active?'Ativa':'Inativa'}</span><button data-edit-category="${c.id}">Editar</button><button data-toggle-category="${c.id}">${c.active?'Inativar':'Ativar'}</button></div>`).join(''):'<p class="empty-state">Nenhuma categoria encontrada.</p>'}</div></section>${categoryEditing?categoryForm():''}</section></main>`}
function categoryForm():string{const c=categoryEditing;return `<div class="modal"><form id="category-form" class="panel modal-card"><h2>${c?.id?'Editar':'Nova'} categoria</h2><label>Nome<input autofocus name="name" value="${c?.name??''}" required/></label><label>Descrição<input name="description" value="${c?.description??''}"/></label><label>Margem padrão (%)<input name="margin" type="number" min="0" max="1000" value="${((c?.defaultMarginPercentage??0)/100).toFixed(2)}"/></label><div><button class="primary">Salvar</button><button type="button" id="cancel-category">Cancelar</button></div></form></div>`}
function productsTemplate():string{return `<main class="shell">${sidebar()}<section class="dashboard"><header><div><p class="eyebrow">CADASTROS</p><h1>Produtos</h1></div><button id="new-product" class="primary">Novo produto</button></header><div class="catalog-tools"><input id="product-search" placeholder="Buscar nome, SKU ou código de barras"/><select id="product-category"><option value="">Todas categorias</option>${categories.filter(c=>c.active).map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}</select><select id="product-status"><option value="">Todos status</option><option value="active">Ativos</option><option value="inactive">Inativos</option></select><label class="check"><input id="low-stock" type="checkbox"/> Estoque baixo</label></div><p id="catalog-message" class="auth-error"></p><section class="panel"><div class="product-head">Nome | Código | Categoria | Custo | Venda | Margem | Estoque | Status | Ações</div>${products.length?products.map(p=>`<div class="catalog-row ${p.currentStockMilli<=p.minimumStockMilli?'low-stock':''}"><b>${p.name}</b><span>${p.barcode??'—'}</span><span>${p.categoryName??'—'}</span><span>${money(p.costPriceCents)}</span><span>${money(p.salePriceCents)}</span><span>${pct(p.marginPercentage)}</span><span>${(p.currentStockMilli/1000).toFixed(3)}</span><span class="status ${p.active?'on':'off'}">${p.active?'Ativo':'Inativo'}</span><button data-edit-product="${p.id}">Editar</button><button data-toggle-product="${p.id}">${p.active?'Inativar':'Ativar'}</button></div>`).join(''):'<p class="empty-state">Nenhum produto encontrado.</p>'}</section>${productEditing?productForm():''}</section></main>`}
function productForm():string{const p=productEditing;const f=(n:string,l:string,v:string|number='')=>`<label>${l}<input name="${n}" value="${v}"/></label>`;return `<div class="modal"><form id="product-form" class="panel modal-card"><h2>${p?.id?'Editar':'Novo'} produto</h2><div class="form-grid">${f('name','Nome',p?.name??'')}${f('description','Descrição',p?.description??'')}<label>Categoria<select name="categoryId"><option value="">Sem categoria</option>${categories.filter(c=>c.active||c.id===p?.categoryId).map(c=>`<option ${c.id===p?.categoryId?'selected':''} value="${c.id}">${c.name}</option>`).join('')}</select></label>${f('sku','SKU',p?.sku??'')}${f('barcode','Código de barras',p?.barcode??'')}${f('unit','Unidade',p?.unit??'UN')}${f('cost','Custo (R$)',p? (p.costPriceCents/100).toFixed(2):'0,00')}${f('margin','Margem (%)',p?(p.marginPercentage/100).toFixed(2):'0')}${f('sale','Preço de venda (R$)',p?(p.salePriceCents/100).toFixed(2):'0,00')}<label>Estoque atual<input readonly value="${p?(p.currentStockMilli/1000).toFixed(3):'0,000'}"/></label>${f('minimum','Estoque mínimo',p?(p.minimumStockMilli/1000).toFixed(3):'0,000')}<label>Ativo<select name="active"><option value="true" ${p?.active!==false?'selected':''}>Sim</option><option value="false" ${p?.active===false?'selected':''}>Não</option></select></label></div><div><button class="primary">Salvar</button><button type="button" id="cancel-product">Cancelar</button></div></form></div>`}
function render(): void { const app = document.querySelector('#app'); if (!app) return; app.innerHTML = currentView === 'login' ? loginTemplate() : currentView === 'change-password' ? changePasswordTemplate() : currentView === 'company' ? companyTemplate() : currentView === 'categories' ? categoriesTemplate() : currentView === 'products' ? productsTemplate() : currentView === 'placeholder' ? placeholderTemplate() : dashboardTemplate(); bind(); }
async function loadCategories(q=''){const r=await window.pdv.categories.list(q);if(r.success)categories=r.data??[]}
async function loadProducts(){const q=(document.querySelector<HTMLInputElement>('#product-search')?.value??'');const c=Number(document.querySelector<HTMLSelectElement>('#product-category')?.value)||undefined;const low=document.querySelector<HTMLInputElement>('#low-stock')?.checked??false;const r=await window.pdv.products.list(q,c,low);if(r.success){products=r.data??[];const s=document.querySelector<HTMLSelectElement>('#product-status')?.value;if(s)products=products.filter(p=>s==='active'?p.active:!p.active)}}
function error(message?: string): void { const target = document.querySelector('#auth-error, #company-message'); if (target) target.textContent = message ?? ''; }
async function goCompany(): Promise<void> {
  currentView = 'company';
  render();
  const message = document.querySelector<HTMLElement>('#company-message');
  if (message) message.textContent = 'Carregando dados da empresa…';
  try {
    const response = await window.pdv.company.get();
    if (!response.success) throw new Error(response.error?.message ?? 'Não foi possível carregar a empresa.');
    company = response.data ?? null;
    render();
  } catch (cause) {
    const errorMessage = cause instanceof Error ? cause.message : 'Não foi possível carregar a empresa.';
    const target = document.querySelector<HTMLElement>('#company-message');
    if (target) {
      target.innerHTML = `${errorMessage} <button type="button" id="retry-company">Tentar novamente</button>`;
      document.querySelector('#retry-company')?.addEventListener('click', () => void goCompany());
    }
    console.error('Falha ao carregar Dados da empresa.', cause);
  }
}
function goPlaceholder(title: string): void { placeholderTitle = title; currentView = 'placeholder'; render(); }
function bind(): void {
  document.querySelectorAll<HTMLButtonElement>('.theme-toggle').forEach((button) => button.addEventListener('click', () => document.body.classList.toggle('dark')));
  document.querySelector('#nav-dashboard')?.addEventListener('click', () => { currentView = 'dashboard'; render(); });
  document.querySelector('#nav-sales')?.addEventListener('click', () => goPlaceholder('Vendas'));
  document.querySelector('#nav-products')?.addEventListener('click', async () => { await loadCategories(); await loadProducts(); currentView='products'; render(); });
  document.querySelector('#nav-categories')?.addEventListener('click', async () => { await loadCategories(); currentView='categories'; render(); });
  document.querySelector('#nav-customers')?.addEventListener('click', () => goPlaceholder('Clientes'));
  document.querySelector('#nav-company')?.addEventListener('click', () => void goCompany());
  document.querySelector('#back-dashboard')?.addEventListener('click', () => { currentView = 'dashboard'; render(); });
  document.querySelector('#logout-button')?.addEventListener('click', async () => { await window.pdvMaster.auth.logout(); user = null; company = null; currentView = 'login'; render(); });
  document.querySelector('#open-menu')?.addEventListener('click', () => document.querySelector('#sidebar')?.classList.add('open'));
  document.querySelector('#close-menu')?.addEventListener('click', () => document.querySelector('#sidebar')?.classList.remove('open'));
  document.querySelector<HTMLFormElement>('#login-form')?.addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget as HTMLFormElement); const response = await window.pdvMaster.auth.login(String(form.get('email') ?? ''), String(form.get('password') ?? '')); if (!response.success || !response.data) return error(response.error?.message); user = response.data; currentView = user.mustChangePassword ? 'change-password' : 'dashboard'; render(); });
  document.querySelector<HTMLFormElement>('#change-password-form')?.addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget as HTMLFormElement); const response = await window.pdvMaster.auth.changePassword(String(form.get('currentPassword') ?? ''), String(form.get('newPassword') ?? '')); if (!response.success || !response.data) return error(response.error?.message); user = response.data; currentView = 'dashboard'; render(); });
  const form = document.querySelector<HTMLFormElement>('#company-form'); form?.addEventListener('input', () => { companyDirty = true; }); form?.addEventListener('submit', async (event) => { event.preventDefault(); const button = document.querySelector<HTMLButtonElement>('#company-save'); if (button?.disabled) return; if (button) button.disabled = true; const values = Object.fromEntries(new FormData(event.currentTarget as HTMLFormElement).entries()) as Record<string, string>; const response = await window.pdv.company.save(values); if (!response.success || !response.data) error(response.error?.message); else { company = response.data; companyDirty = false; error('Alterações salvas com sucesso.'); } if (button) button.disabled = false; });
  document.querySelector('#new-category')?.addEventListener('click',()=>{categoryEditing={} as CategoryView;render()});document.querySelectorAll('[data-edit-category]').forEach(x=>x.addEventListener('click',()=>{categoryEditing=categories.find(c=>c.id===Number((x as HTMLElement).dataset.editCategory))??null;render()}));document.querySelectorAll('[data-toggle-category]').forEach(x=>x.addEventListener('click',async()=>{if(!confirm('Alterar situação da categoria?'))return;const c=categories.find(v=>v.id===Number((x as HTMLElement).dataset.toggleCategory));if(c){await window.pdv.categories.setActive(c.id,!c.active);await loadCategories();render()}}));document.querySelector('#cancel-category')?.addEventListener('click',()=>{categoryEditing=null;render()});document.querySelector<HTMLFormElement>('#category-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const d={name:String(f.get('name')),description:String(f.get('description')),defaultMarginPercentage:Math.round(Number(String(f.get('margin')).replace(',','.'))*100)};const r=categoryEditing?.id?await window.pdv.categories.update(categoryEditing.id,d):await window.pdv.categories.create(d);if(!r.success)return error(r.error?.message);categoryEditing=null;await loadCategories();render()});document.querySelector('#category-search')?.addEventListener('input',async e=>{await loadCategories((e.target as HTMLInputElement).value);render()});
  document.querySelector('#new-product')?.addEventListener('click',()=>{productEditing={} as ProductView;render()});document.querySelectorAll('[data-edit-product]').forEach(x=>x.addEventListener('click',()=>{productEditing=products.find(p=>p.id===Number((x as HTMLElement).dataset.editProduct))??null;render()}));document.querySelectorAll('[data-toggle-product]').forEach(x=>x.addEventListener('click',async()=>{const p=products.find(v=>v.id===Number((x as HTMLElement).dataset.toggleProduct));if(p){await window.pdv.products.setActive(p.id,!p.active);await loadProducts();render()}}));document.querySelector('#cancel-product')?.addEventListener('click',()=>{productEditing=null;render()});document.querySelector<HTMLFormElement>('#product-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget),num=(n:string)=>Math.round(Number(String(f.get(n)).replace(',','.'))*(n==='minimum'?1000:100));const d={name:String(f.get('name')).trim(),description:String(f.get('description')).trim(),categoryId:String(f.get('categoryId'))||undefined,sku:String(f.get('sku')).trim(),barcode:String(f.get('barcode')).trim(),unit:String(f.get('unit')).trim(),costPriceCents:num('cost'),salePriceCents:num('sale'),minimumStockMilli:num('minimum'),active:String(f.get('active'))==='true'};const r=productEditing?.id?await window.pdv.products.update(productEditing.id,d):await window.pdv.products.create(d);if(!r.success)return error(r.error?.message);productEditing=null;await loadProducts();render()});document.querySelectorAll('#product-search,#product-category,#product-status,#low-stock').forEach(x=>x.addEventListener('input',async()=>{await loadProducts();render()}));
}
async function bootstrap(): Promise<void> { const response = await window.pdvMaster.auth.session(); if (response.success && response.data) { user = response.data; const result = await window.pdv.company.get(); company = result.data ?? null; currentView = user.mustChangePassword ? 'change-password' : 'dashboard'; } render(); }
void bootstrap();
window.addEventListener('beforeunload', (event) => { if (currentView === 'company' && companyDirty) { event.preventDefault(); event.returnValue = ''; } });
